### ISSUE TITLE
Noob question - How to Auto Load Ad

### ISSUE THREAD

**Issue by holanino** [EMI-INDO/emi-indo-cordova-plugin-admob#10]
Thank you again for this great plugin. I am wanting to auto load an Ad but I am having difficulty.

In version 3 or 4 I would use the following to load the Ad from a <script> tag in html.

cordova.plugins.emiAdmobPlugin.loadInterstitialAd(AdUnitId);

I am not able to do this the latest 9 release, what I am I missing?

**Comment by EMI-INDO** [comment]
@holanino 

- check the release notes

https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob/releases/tag/v.1.0.9

**Comment by holanino** [comment]
For example, this will not auto "load" the Interstitial Ad


<html>
<head>
    <script type="text/javascript" src="cordova.js"></script>
</head>
<body>

<script>

// Load Interstitial Ad

let loadInterstitialAd = () => {
    cordova.plugins.emiAdmobPlugin.loadInterstitialAd(
    AdUnitId = "ca-app-pub-3940256099942544/1033173712",
	npa = "1", // String | 0 | 1
    responseInfo = true, // boolean

    // Optional
	(info) => { alert(info) }, 
    (error) => { alert(error)
    
    });
}

// Show Interstitial Ad

let showInterstitialAd = () => {
    cordova.plugins.emiAdmobPlugin.showInterstitialAd();
}

document.addEventListener("deviceready", function(){

// Before loading ads, have your app initialize the Google Mobile Ads SDK by calling
// This needs to be done only once, ideally at app launch.

cordova.plugins.emiAdmobPlugin.initialize(
    // Optional
    (info) => { console.log(info) },
    (error) => { alert(error)

    });

// Instruction: https://developers.google.com/admob/android/global-settings

cordova.plugins.emiAdmobPlugin.globalSettings(

    setAppMuted = true, // Type Boolean default: true
    setAppVolume = 1.0, // Type float
    enableSameAppKey = false, // Type Boolean default: false
      
      // Optional
    (info) => { console.log(info) },
    (error) => { alert(error)

    });
	
	
	  // You can see the value when the ad is loaded, set responseInfo = true
     // Instruction: https://developers.google.com/admob/android/targeting
     // Overview: https://developers.google.com/android/reference/com/google/android/gms/ads/RequestConfiguration

    cordova.plugins.emiAdmobPlugin.targeting(
      TagForChildDirectedTreatment = 0, // value: 0 | -1 | 1
      TagForUnderAgeOfConsent = 0, // // value: 0 | -1 | 1
      MaxAdContentRating = "G", // value: G | MA | PG | T | ""

      // Optional
     (info) => { console.log(info) },
     (error) => { alert(error)

     });
 
document.addEventListener('on.SdkInitializationComplete', () => {

alert("on Sdk Initialization Complete");

});

// Interstitial EVENT

/*
on.InterstitialAdLoaded
on.InterstitialAdFailedToLoad
on.InterstitialAdClicked
on.InterstitialAdDismissedFullScreenContent
on.InterstitialAdFailedToShowFullScreenContent
on.InterstitialAdImpression
on.InterstitialAdShowedFullScreenContent
*/

document.addEventListener('on.InterstitialAdLoaded', () => {

alert("on Interstitial Ad Loaded");

});


cordova.plugins.emiAdmobPlugin.loadInterstitialAd(AdUnitId);

}, false);

</script>


<p> <button onclick="loadInterstitialAd();">Load Interstitial Ad</button></p>
<p> <button onclick="showInterstitialAd();">Show Interstitial Ad</button></p>



</body>
</html>

**Comment by holanino** [comment]
For example this will no auto "load" the ad.


<html>
<head>
    <script type="text/javascript" src="cordova.js"></script>
</head>
<body>

<script>

// Load Interstitial Ad

let loadInterstitialAd = () => {
    cordova.plugins.emiAdmobPlugin.loadInterstitialAd(
    AdUnitId = "ca-app-pub-3940256099942544/1033173712",
	npa = "1", // String | 0 | 1
    responseInfo = true, // boolean

    // Optional
	(info) => { alert(info) }, 
    (error) => { alert(error)
    
    });
}

// Show Interstitial Ad

let showInterstitialAd = () => {
    cordova.plugins.emiAdmobPlugin.showInterstitialAd();
}

document.addEventListener("deviceready", function(){

// Before loading ads, have your app initialize the Google Mobile Ads SDK by calling
// This needs to be done only once, ideally at app launch.

cordova.plugins.emiAdmobPlugin.initialize(
    // Optional
    (info) => { console.log(info) },
    (error) => { alert(error)

    });

// Instruction: https://developers.google.com/admob/android/global-settings

cordova.plugins.emiAdmobPlugin.globalSettings(

    setAppMuted = true, // Type Boolean default: true
    setAppVolume = 1.0, // Type float
    enableSameAppKey = false, // Type Boolean default: false
      
      // Optional
    (info) => { console.log(info) },
    (error) => { alert(error)

    });
	
	
	  // You can see the value when the ad is loaded, set responseInfo = true
     // Instruction: https://developers.google.com/admob/android/targeting
     // Overview: https://developers.google.com/android/reference/com/google/android/gms/ads/RequestConfiguration

    cordova.plugins.emiAdmobPlugin.targeting(
      TagForChildDirectedTreatment = 0, // value: 0 | -1 | 1
      TagForUnderAgeOfConsent = 0, // // value: 0 | -1 | 1
      MaxAdContentRating = "G", // value: G | MA | PG | T | ""

      // Optional
     (info) => { console.log(info) },
     (error) => { alert(error)

     });
 
document.addEventListener('on.SdkInitializationComplete', () => {

alert("on Sdk Initialization Complete");

});

// Interstitial EVENT

/*
on.InterstitialAdLoaded
on.InterstitialAdFailedToLoad
on.InterstitialAdClicked
on.InterstitialAdDismissedFullScreenContent
on.InterstitialAdFailedToShowFullScreenContent
on.InterstitialAdImpression
on.InterstitialAdShowedFullScreenContent
*/

document.addEventListener('on.InterstitialAdLoaded', () => {

alert("on Interstitial Ad Loaded");

});


cordova.plugins.emiAdmobPlugin.loadInterstitialAd(AdUnitId);

}, false);

</script>


<p> <button onclick="loadInterstitialAd();">Load Interstitial Ad</button></p>
<p> <button onclick="showInterstitialAd();">Show Interstitial Ad</button></p>



</body>
</html>

**Comment by holanino** [comment]
Came up with this solution even though not sure how it works. 

It Auto loads the Ad and auto Shows the Ad.


```
<html>
<head>
    <script type="text/javascript" src="cordova.js"></script>
</head>
<body>

<script>
document.addEventListener("deviceready", function(){

    // Load Interstitial Ad
    cordova.plugins.emiAdmobPlugin.loadInterstitialAd(
        "ca-app-pub-3940256099942544/1033173712", // AdUnitId
        "1", // npa
        true, // responseInfo

        // Optional
        (info) => { 
      //      alert(info);
            showInterstitialAd(); // Call showInterstitialAd() after the ad is loaded
        }, 
        (error) => { 
       //     alert(error); 
        }
    );

    // Show Interstitial Ad
    let showInterstitialAd = () => {
        cordova.plugins.emiAdmobPlugin.showInterstitialAd();
    };

    // Before loading ads, have your app initialize the Google Mobile Ads SDK by calling
    // This needs to be done only once, ideally at app launch.
    cordova.plugins.emiAdmobPlugin.initialize(
        // Optional
    //    (info) => { console.log(info); },
    //    (error) => { alert(error); }
    );

    // Instruction: https://developers.google.com/admob/android/global-settings
    cordova.plugins.emiAdmobPlugin.globalSettings(
        true, // setAppMuted
        1.0, // setAppVolume
        false, // enableSameAppKey
        // Optional
     //   (info) => { console.log(info); },
     //   (error) => { alert(error); }
    );

    // You can see the value when the ad is loaded, set responseInfo = true
    // Instruction: https://developers.google.com/admob/android/targeting
    // Overview: https://developers.google.com/android/reference/com/google/android/gms/ads/RequestConfiguration
    cordova.plugins.emiAdmobPlugin.targeting(
        0, // TagForChildDirectedTreatment
        0, // TagForUnderAgeOfConsent
        "G", // MaxAdContentRating
        // Optional
    //    (info) => { console.log(info); },
     //   (error) => { alert(error); }
    );

    document.addEventListener('onSdkInitializationComplete', () => {
     //   alert("on Sdk Initialization Complete");
    });

    // Interstitial EVENT
    /*
    on.InterstitialAdLoaded
    on.InterstitialAdFailedToLoad
    on.InterstitialAdClicked
    on.InterstitialAdDismissedFullScreenContent
    on.InterstitialAdFailedToShowFullScreenContent
    on.InterstitialAdImpression
    on.InterstitialAdShowedFullScreenContent
    */
    document.addEventListener('onInterstitialAdLoaded', () => {
    //    alert("on Interstitial Ad Loaded");
    });

}, false);

</script>
<p> <button onclick="loadInterstitialAd();">Load Interstitial Ad</button></p>
<p> <button onclick="showInterstitialAd();">Show Interstitial Ad</button></p>

</body>
</html>
```

**Comment by krestia** [comment]
there is show nothing in my .html code :
`<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *; img-src 'self' data: content:;">
        <meta name="format-detection" content="telephone=no">
        <meta name="msapplication-tap-highlight" content="no">
        <meta name="viewport" content="initial-scale=1, width=device-width, viewport-fit=cover">
        <meta name="color-scheme" content="light dark">
        <link rel="stylesheet" href="css/index.css">
        <title>Hello World</title>
    </head>
    <body>
        <div class="app">
            <h1>Apache Cordova</h1>
            <div id="deviceready" class="blink">
                <p class="event listening">Connecting to Device</p>
                <p class="event received">Device is Ready</p>
            </div>
        </div>
        <script src="cordova.js"></script>
        <script src="js/index.js"></script>
		
		<script>


// load App Open Ad

let loadAppOpenAd = () => {
    cordova.plugins.emiAdmobPlugin.loadAppOpenAd(
    AdUnitId = "ca-app-pub-3940256099942544/3419835294",
    npa = "1", // String | 0 | 1
    responseInfo = true, // boolean

    // Optional
	(info) => { alert(info) },
    (error) => { alert(error)

    });
}

// Show App Open Ad

let showAppOpenAd = () => {
    cordova.plugins.emiAdmobPlugin.showAppOpenAd();
}


/// setting banner size: 
/*          
BANNER
FLUID 
LARGE_BANNER
MEDIUM_RECTANGLE
FULL_BANNER
LEADERBOARD
(Smart Banners = DEPRECATED)
Inline_adaptive
Anchored_adaptive
default: Anchored_FULL_WIDTH

adaptiveWidth = 320 // number (only adaptive banner)

*/
/// setting banner position:  
/*     
top-right
top-center
left
center
right
bottom-center
bottom-right
default: "bottom-left"
*/

//  Banner Adaptive

let showBannerAdaptive = () => {
    cordova.plugins.emiAdmobPlugin.showBannerAd(
    AdUnitId = "ca-app-pub-3940256099942544/6300978111",
	npa = "1", // String | 0 | 1
    position = "bottom-center",
    size = "Anchored_FULL_WIDTH", // | Inline_adaptive | Anchored_adaptive | default: Anchored_FULL_WIDTH
    adaptiveWidth = 320,
	responseInfo = true, // boolean

    // Optional
	(info) => { alert(info) },
    (error) => { alert(error)

    });
}

//  not Adaptive banner

let showBannerNotAdaptive = () => {
    cordova.plugins.emiAdmobPlugin.showBannerAd(
    AdUnitId = "ca-app-pub-3940256099942544/6300978111",
	npa = "1", // String | 0 | 1
    position = "bottom-center",
    size = "FLUID",
	adaptiveWidth = 320,
	responseInfo = true, // boolean
    
    // Optional
	(info) => { alert(info) },
    (error) => { alert(error)

    });
}

// Remove Banner

let removeBannerAd = () => {
    cordova.plugins.emiAdmobPlugin.removeBannerAd();
}


// Load Interstitial Ad

let loadInterstitialAd = () => {
    cordova.plugins.emiAdmobPlugin.loadInterstitialAd(
    AdUnitId = "ca-app-pub-3940256099942544/1033173712",
	npa = "1", // String | 0 | 1
    responseInfo = true, // boolean

    // Optional
	(info) => { alert(info) }, 
    (error) => { alert(error)
    
    });
}

// Show Interstitial Ad

let showInterstitialAd = () => {
    cordova.plugins.emiAdmobPlugin.showInterstitialAd();
}

// load Rewarded Interstitial Ad

let loadRewardedInterstitialAd = () => {
    cordova.plugins.emiAdmobPlugin.loadRewardedInterstitialAd(
    AdUnitId = "ca-app-pub-3940256099942544/5354046379",
	npa = "1", // String | 0 | 1
    responseInfo = true, // boolean
   
    // Optional
	(info) => { alert(info) },
    (error) => { alert(error)

    });
}


// Show Rewarded Interstitial Ad

const showRewardedInterstitialAd = () => {
    cordova.plugins.emiAdmobPlugin.showRewardedInterstitialAd();
}

// Load Rewarded Ad

let loadRewardedAd = () => {
    cordova.plugins.emiAdmobPlugin.loadRewardedAd(
    AdUnitId = "ca-app-pub-3940256099942544/5224354917",
	npa = "1", // String | 0 | 1
    responseInfo = true, // boolean
   
    // Optional
    (info) => { alert(info) },
    (error) => { alert(error)

    });
}

// Show Rewarded Ad

let showRewardedAd = () => {
    cordova.plugins.emiAdmobPlugin.showRewardedAd();
}



document.addEventListener("deviceready", function(){

// Before loading ads, have your app initialize the Google Mobile Ads SDK by calling
// This needs to be done only once, ideally at app launch.

cordova.plugins.emiAdmobPlugin.initialize(
    // Optional
    (info) => { console.log(info) },
    (error) => { alert(error)

    });

// Instruction: https://developers.google.com/admob/android/global-settings

cordova.plugins.emiAdmobPlugin.globalSettings(

    setAppMuted = true, // Type Boolean default: true
    setAppVolume = 1.0, // Type float
    enableSameAppKey = false, // Type Boolean default: false
      
      // Optional
    (info) => { console.log(info) },
    (error) => { alert(error)

    });
	
	
	  // You can see the value when the ad is loaded, set responseInfo = true
     // Instruction: https://developers.google.com/admob/android/targeting
     // Overview: https://developers.google.com/android/reference/com/google/android/gms/ads/RequestConfiguration

    cordova.plugins.emiAdmobPlugin.targeting(
      TagForChildDirectedTreatment = 0, // value: 0 | -1 | 1
      TagForUnderAgeOfConsent = 0, // // value: 0 | -1 | 1
      MaxAdContentRating = "G", // value: G | MA | PG | T | ""

      // Optional
     (info) => { console.log(info) },
     (error) => { alert(error)

     });
 

document.addEventListener('on.SdkInitializationComplete', () => {

alert("on Sdk Initialization Complete");


});

// AppOpenAd EVEN

/*
on.open.loaded
on.open.failed.loaded
on.open.dismissed
on.open.failed.show
on.open.show
*/


document.addEventListener('on.open.loaded', () => {

alert("on app open loaded");

});



// BANNER EVENT

/*
on.bannerAdClicked
on.bannerAdClosed
on.bannerAdFailedToLoad
on.bannerAdImpression
on.bannerAdLoaded
on.bannerAdOpened
*/
document.addEventListener('on.bannerAdLoaded', () => {

alert("on banner Ad Loaded");

});



// Interstitial EVENT

/*
on.InterstitialAdLoaded
on.InterstitialAdFailedToLoad
on.InterstitialAdClicked
on.InterstitialAdDismissedFullScreenContent
on.InterstitialAdFailedToShowFullScreenContent
on.InterstitialAdImpression
on.InterstitialAdShowedFullScreenContent
*/

document.addEventListener('on.InterstitialAdLoaded', () => {

alert("on Interstitial Ad Loaded");

});


// Rewarded Interstitial EVENT

/*
on.RewardedInterstitialAdLoaded
on.RewardedInterstitialAdFailedToLoad
on.rewardedInterstitialAdClicked
on.rewardedInterstitialAdDismissedFullScreenContent
on.rewardedInterstitialAdFailedToShowFullScreenContent
on.rewardedInterstitialAdImpression
on.rewardedInterstitialAdShowedFullScreenContent
on.rewardedInterstitial.rewarded
*/

document.addEventListener('on.RewardedInterstitialAdLoaded', () => {

alert("on Rewarded Interstitial Loaded");

});


// Rewarded EVENT

/*
on.RewardedAdFailedToLoad
on.RewardedAdLoaded
on.rewardedAdClicked
on.rewardedAdDismissedFullScreenContent
on.rewardedAdFailedToShowFullScreenContent
on.rewardedAdImpression
on.rewardedAdShowedFullScreenContent
on.rewarded.rewarded
*/

document.addEventListener('on.RewardedAdLoaded', () => {

alert("on Rewarded Ad Loaded");

});



}, false);

</script>

<p> <button onclick="loadAppOpenAd();">load App Open Ad</button></p>
<p> <button onclick="showAppOpenAd();">Show App Open Ad</button></p>

<p> <button onclick="showBannerAdaptive();">Show Banner adaptive</button></p>
<p> <button onclick="showBannerNotAdaptive();">show Banner No Adaptive</button></p>
<p> <button onclick="removeBannerAd();">remove Banner Ad</button></p>

<p> <button onclick="loadInterstitialAd();">Load Interstitial Ad</button></p>
<p> <button onclick="showInterstitialAd();">Show Interstitial Ad</button></p>

<p> <button onclick="loadRewardedInterstitialAd();">Load Rewarded Interstitial</button></p>
<p> <button onclick="showRewardedInterstitialAd();">Show Rewarded Interstitial</button></p>

<p> <button onclick="loadRewardedAd();">Load Rewarded Ad</button></p>
<p> <button onclick="showRewardedAd();">Show Rewarded Ad</button></p>
		
    </body>
</html>`

not sure what i.am missing

**Comment by EMI-INDO** [comment]
@holanino 

## You should learn a lot of javascript and html

- Set up everything you want automatically in the `device ready` block. 

- Below is an example of a `device ready` block 
```
document.addEventListener("deviceready", function(){

// Code

}, false);
```

## For example  Interstitial ad

```
<script>

// Load Interstitial Ad

let loadInterstitialAd = () => {
    cordova.plugins.emiAdmobPlugin.loadInterstitialAd(
    AdUnitId = "ca-app-pub-3940256099942544/1033173712",
    npa = "1", // String | 0 | 1
    responseInfo = true, // boolean (debugging)
    
    // Optional
    (info) => { alert(info) }, 
    (error) => { alert(error)
    
    });
}

// call loadInterstitialAd();


document.addEventListener("deviceready", function(){

// Code

// example auto load Interstitial
loadInterstitialAd();
// showInterstitialAd();




// auto load delete //
// loadAppOpenAd();
// showAppOpenAd();

// banner  auto load a show delete //
//  showBannerAdaptive();
// showBannerNotAdaptive();
// removeBannerAd();

// auto load delete //
// loadRewardedInterstitialAd();
// showRewardedInterstitialAd();

// auto load delete //
// loadRewardedAd();
//showRewardedAd();

// EVENT

//  example auto show ads delete //
document.addEventListener('on.InterstitialAdLoaded', () => {

// showInterstitialAd();

 console.log("on Interstitial Ad Loaded");

});

}, false);

</script>

```

**Comment by EMI-INDO** [comment]
@holanino 

https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob/blob/main/example/auto_load_and_show.html

**Comment by holanino** [comment]
Thank you for the example. I noticed my error also was some unclosed brackets when I commented out some lines during testing.

I am not a developer, I only make wysiwyg apps as a hobby.
