### ISSUE TITLE
Ads are closing after resume the app.

### ISSUE THREAD

**Issue by mjapps-games** [EMI-INDO/emi-indo-cordova-plugin-admob#14]
When an ad is running, and the user switches to another app, the ad should not automatically close. Instead, it should remain paused, and when the user later returns to the first app, the ad should resume from where it stopped, rather than being closed automatically.

**Comment by EMI-INDO** [comment]
@mjapps-games

Your question is not clear, what kind of ads do you mean? rewarded, banner, interstitial?

**Comment by mjapps-games** [comment]
Rewarded and Interstitial ads are closed if the user switches the app. Consider a scenario like this -- the user opted to watch a rewarded ad which is of 30 sec. and watched it for 15 sec. Then he switches to another app -- when he comes back to the prev app the ad is closed. The ad should not be closed and should be continued from the 16th sec.

**Comment by EMI-INDO** [comment]
@mjapps-games 

I didn't find any documentation for it,
admob-plus-cordova also has the same problem.

I'll try to fix it.

**Comment by EMI-INDO** [comment]
Currently I can't do it, cordova.activity is completely destroyed when the app is pushed to the background.

When the app is pushed to the background, the ad activity will enter the condition/event

- on.rewardedInt.ad.skip
- on.rewarded.ad.skip

Example 

```
document.addEventListener('on.rewarded.ad.skip', () => {

console.log(“When the app is pushed to the background”);
console.log(“when the user clicks x/skip ad”);

});
```
