### ISSUE TITLE
Banner ad covers bottom of the page

### ISSUE THREAD

**Issue by rashnk** [EMI-INDO/emi-indo-cordova-plugin-admob#19]
**Expected behavior:**
The banner ad on bottom should not cover the page content, ad should display below the page content

**Steps to reproduce:**
 ```
   let AdUnitId = "ca-app-pub-3940256099942544/6300978111"; // test banner ad
    let npa = "1"; // String | 0 | 1
    let position = "bottom-center";
    //let size = "default"; // Inline_adaptive | Anchored_adaptive | default = Adaptive_FULL_WIDTH
    let size = "BANNER";
    let adaptiveWidth = 320;
    let responseInfo = debug; // boolean
```

**Screenshots**
![image](https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob/assets/12730428/76ff0b94-28cd-4012-9503-a9292c00edff)

**Environment information**

- Cordova CLI version 
	12.0.0 (cordova-lib@12.0.1)
- Cordova platform version
	 android 12.0.1
- Plugins & versions installed in project (including this plugin)
    cordova-plugin-file-opener2 4.0.0 "File Opener2"
cordova-plugin-file 8.0.0 "File"
cordova-plugin-keyboard 1.2.0 "Keyboard"
cordova-plugin-save-image-gallery 0.0.26 "saveImageGallery"
cordova-plugin-save-image 0.3.0 "SaveImage"
cordova-plugin-splashscreen 6.0.2 "Splashscreen"
cordova-plugin-statusbar 3.0.0 "StatusBar"
cordova-plugin-x-socialsharing 6.0.4 "SocialSharing"
emi-indo-cordova-plugin-admob 1.3.9 "emiAdmobPlugin"
es6-promise-plugin 4.2.2 "Promise"

- Dev machine OS and version, e.g.
  Windows 11
        
- Device details
    - _Realme 5 pro
- OS details
    - Android 11
	
- Target Android SDK version
	33

**Comment by carlobs** [comment]
Same here. problem with cordova.

**Comment by rashnk** [comment]
May be the problem with RelativeLayout,
I managed to solve this issue by adjusting the page height as below,
the page height will be set to 93vh once the ad is loaded
![image](https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob/assets/12730428/e15e38b8-ef01-4fb4-a939-268aeed993bc)

**Comment by merbin2012** [comment]
@EMI-INDO Please solve this issue

**Comment by merbin2012** [comment]
@carlobs and @rashnk This issue has been solved. Please refer the following example 
https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob/blob/main/example/www/js/bannerAd.js

`ccordova.plugins.emiAdmobPlugin.styleBannerAd({isOverlapping: true, overlappingHeight: 5, padding: 0, margins: 0 });`

Also, you can solve it by your html & css code,  currently it is in progress, once it is done I will inform you with neat example.

**Comment by merbin2012** [comment]
You can get the height of the banner ad, in `on.banner.load` event. So now you can easy to control the size of the screen based on the screen height.
```
document.addEventListener('on.banner.load', (arg) => {
    let bannerAdHeight=arg.height;
    console.log("on banner load");
});
```

Example

```
const initialWindowInnerHeight=window.innerHeight;

async function adjustWebViewForBanner(adHeight) {


	if(_isOverlappingEnable || !adHeight)
		return;

	const bannerHeightPx = adHeight;
	const anyExtraPixel= 10; 
	
	const currentWindowHeight=window.innerHeight>initialWindowInnerHeight?window.innerHeight:initialWindowInnerHeight;

	const adjustedHeight = (currentWindowHeight) - bannerHeightPx - anyExtraPixel;


	if(!_isBannerAdShowing)
	{
		document.body.style.height = `${currentWindowHeight}px`;
		return;
	}

	// Adjust the WebView height
	document.body.style.height = `${adjustedHeight}px`;
	document.body.style.overflow = "hidden"; // Prevent content from overflowing
  

  }
```
