### ISSUE TITLE
If there is no Ad or frequency capping turn on app crashes.

### ISSUE THREAD

**Issue by holanino** [EMI-INDO/emi-indo-cordova-plugin-admob#2]
First of all thank you for updating and improving the plugin from the old admob plus. 

I have an issue, when there is no Interstitial Ad to show the app crashes.

I have used the Test Ad and it works I switch to my own Ad and it works. But if I cap (put a limit) so it will not show an Interstitial Ad than 1 every hour, the app crashes. When I reopen app it keeps crashing when I go the the section the Interstitial should show. I turn the Interstitial limit off and the app works again.

Any suggestions?

(Also example if I click the Show Interstitial button  before clicking Load Interstitial button the app crashes.)

**Comment by EMI-INDO** [comment]
`emi-indo-cordova-plugin-admob@0.0.3`

**Rename events or AdUnitId**  [https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob/blob/main/example/index.html](url)

note release [https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob/releases/tag/v.0.0.3](url)
