### ISSUE TITLE
ios bug

### ISSUE THREAD

**Issue by boazn0** [EMI-INDO/emi-indo-cordova-plugin-admob#20]
I'm using admob ver. 1.4.0
xcode 15.0.1

I install the plugin like in this youtube https://www.youtube.com/watch?v=vfKGsWZdhSE (from here https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob/discussions/3)

the build was successful but when I fire this JS I get an error
```

cordova.plugins.emiAdmobPlugin.initialize(	);
cordova.plugins.emiAdmobPlugin.loadBannerAd(
				    bannerAdUnitId = "ca-app-pub-3940256099942544/2934735716",
				npa = "1", // String | 0 | 1
				position = "bottom-center",	
				size = "default",    
			);
cordova.plugins.emiAdmobPlugin.showBannerAd();
```

 this what the xcode refer to 
Thread 1: Swift runtime failure: Index out of range
        let bannerAdUnitId = command.arguments[0] as? String ?? ""

emiAdmobPlugin.swift:36

**Comment by EMI-INDO** [comment]
@boazn0 

### plugin upgrade new API
- ios swift migration to objective c.
- works just like an android.
- actions, events just like android.
- New documentation, 
- New README.md, 
- New basic index.html example.

https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob/blob/main/README.md
https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob/tree/main/example
