### ISSUE TITLE
App Reject by google Play with this plugin

### ISSUE THREAD

**Issue by krestia** [EMI-INDO/emi-indo-cordova-plugin-admob#21]
# Bug report

- [x] I confirm this is a suspected bug or issue that will affect other users

- [x] I have reproduced the issue using the [example project](https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob/blob/main/example/index.html) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob/blob/main/README.md) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

How to resolves this?
the plugin is working

**Expected behavior:**
but has been rejected by google :
App Status: Rejected
Your app has been rejected and wasn't published due to the policy issue(s) listed below. If you submitted an update, the previous version of your app is still available on Google Play.

Issue found: Invalid Data safety form
We reviewed your app’s Data safety form in Play Console and found discrepancies between it and how the app collects and shares user data. All apps are required to complete an accurate Data safety form that discloses their data collection and sharing practices - this is required even if your app does not collect any user data.

We detected user data transmitted off device that you have not disclosed in your app’s Data safety form as user data collected.

You must ensure that your app’s Data safety section accurately reflects your app’s data collection, sharing, and handling practices. This includes data collected and handled through any third-party libraries or SDKs used in your app. When available, we’ve included details on SDKs that contain code similar to the code in your APK that may be sending user data off device. You can check if your app uses any of these SDKs, but note that this list of SDKs may not be exhaustive. You must review and account for all data collected and shared by your app.

Issue details

We found an issue in the following area(s):

Version code 101022: Policy Declaration - Data Safety Section: Device Or Other IDs Data Type - Device Or Other IDs (some common examples may include Advertising ID, Android ID, IMEI, BSSID, MAC address)

Permissions : 
android.permission.ACCESS_ADSERVICES_AD_ID, android.permission.ACCESS_ADSERVICES_ATTRIBUTION, android.permission.ACCESS_ADSERVICES_TOPICS, android.permission.ACCESS_NETWORK_STATE, android.permission.FOREGROUND_SERVICE, android.permission.INTERNET, android.permission.WAKE_LOCK, com.google.android.gms.permission.AD_ID

**Steps to reproduce:**
normal , working

**Screenshots**

**Environment information**

- Cordova CLI version 
	- `10.0.0 (cordova-lib@10.1.0)`
- Cordova platform version
	- `Installed platforms:
  android 12.0.0
Available platforms:
  browser ^6.0.0
  electron ^1.1.1
  windows ^7.0.0
- Plugins & versions installed in project (including this plugin)
    - `emi-indo-cordova-plugin-admob 1.4.2 "emiAdmobPlugin"`

**Related code:**
```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**
<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

**Comment by EMI-INDO** [comment]
@krestia 

it's just an error setting the app content in the google play consile account.

This plugin includes com.google.android.gms.permission.AD_ID

https://developers.google.com/interactive-media-ads/docs/sdks/android/dai/android-12

Once the app content is updated, send it for review,
If it is still rejected, it means that there are still wrong settings.

**Comment by EMI-INDO** [comment]
![Screenshot 12-14-2023 18 41 25](https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob/assets/78555833/8f25f3e4-6ced-431a-8110-e4a735509974)
![Screenshot 12-14-2023 18 43 21](https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob/assets/78555833/941c52b1-c48b-415c-9fee-4d1caa68a382)

**Comment by EMI-INDO** [comment]
Fill in all the data correctly, because admob ads collect data.

**Comment by krestia** [comment]
@EMI-INDO  thanks,
but just to be clear,
if that the problem, why after i remove request consent and uninstalling [emi-indo-cordova-plugin-consent](https://github.com/EMI-INDO/emi-indo-cordova-plugin-consent) the problem solved?

**Comment by EMI-INDO** [comment]
@krestia 
DEPRECATED `emi-indo-cordova-plugin-consent` UMP SDK 2.0.0 

`emi-indo-cordova-plugin-admob` Admob SDK 22.6.0 Including UMP SDK 2.1.0

If you install `emi-indo-cordova-plugin-consent` then UMP SDK will install a different SDK version 2.0.0 and 2.1.0

so now just install `emi-indo-cordova-plugin-admob`

**Comment by EMI-INDO** [comment]
next release https://support.google.com/admob/answer/9999955?hl=en

Like IAB TCString expires after 13 months, 
TCString must be deleted, 
the user must regain permission every 13 months.

I am working on this feature.

**Comment by krestia** [comment]
@EMI-INDO 
thank you,
may you can add more example to showing the privacy option form, because in won't showing for me. Note : i didn't use 
<label for="event">Debug Event All response :</label>
    <textarea id="event" name="event" rows="15" cols="40"></textarea>

sorry for requesting in this comment.

**Comment by EMI-INDO** [comment]
@krestia 

plugin updated. v1.4.4
add new variable setDebugGeography = false | true 
- remove plugin, add it back.

- Methods: 
```
const config_globalSettings = [

setAppMuted = false, //  default: false
setAppVolume = 1, //  float: default: 1
enableSameAppKey = false, // default: false
npa = "1", // string "0" | "1"
enableCollapsible = true, // (BETA) activate the collapsible banner ads
responseInfo = false, // default: false
setDebugGeography = true // default: false

]

cordova.plugins.emiAdmobPlugin.globalSettings(config_globalSettings);


// call cordova.plugins.emiAdmobPlugin.getConsentRequest( (ststus) => { console.log("Consent Status: " + ststus) });


```
- Note 
**setDebugGeography**

Testing is very easy, no need for VPN, TEST-DEVICE-HASHED-ID, or anything else, everything has been made programmatically.
must be false if the application is released to the play store / app store. consent from will continue to be called regardless of its status 0,1,2,3, until the value is changed to false.

**Comment by krestia** [comment]
@EMI-INDO 

unfortunately, after updating plugin, it causes bank screen for me.

using this in my index.js
`const config_AppOpenAd = [adUnitId = "ca-app-pub-3940256099942544/9257395921", autoShow = false ];

//load
let loadAppOpenAd = () => {
   
    //cordova.plugins.emiAdmobPlugin.loadAppOpenAd(config_AppOpenAd);
    // Or like this
    cordova.plugins.emiAdmobPlugin.loadAppOpenAd([adUnitId = "ca-app-pub-3940256099942544/9257395921", autoShow = false ]);
    // call loadAppOpenAd();`

and uses button in index.html
`<script src="cordova.js"></script>
        <script src="js/index.js"></script>
        
        <p> <button onclick="loadAppOpenAd();">load App Open Ad</button></p>`

nothing load, nothing show and return error from android studio :

"I/chromium: [INFO:CONSOLE(12)] "Uncaught ReferenceError: loadAppOpenAd is not defined", source: https://localhost/index.html (12)"

**Comment by emi415064** [comment]
@krestia 

I just tested it works fine.

your code is not clear,
incomplete,

sorry I can't help...

**Comment by krestia** [comment]
@emi415064 

Yes, i think it just because the config is in array, like :
`const config_AppOpenAd = [
	adUnitId = "ca-app-pub-3940256099942544/9257395921",
	autoShow = false 
	];`
when i use variabel, like : 
`var openAdId ="";`
in order to change the adUnitId in runtime, but i can't change the adUnitId dynamically from the variabel, :
`const config_AppOpenAd = [
	adUnitId = openAdId,
	autoShow = false 
	];`
that methode always return NULL :
`W/ConnectionStatusConfig: Dynamic lookup for intent failed for action: com.google.android.gms.ads.service.START
E/Parcel: Reading a NULL string not supported here.
D/CordovaWebViewImpl: >>> loadUrl(javascript:cordova.fireDocumentEvent('on.appOpenAd.failed.loaded');)
I/Ads: Ad failed to load : 1

before (in version 1.4.2) i can change the AdUnitId by variable like this methode:
`let loadAppOpenAd = () => {

    cordova.plugins.emiAdmobPlugin.loadAppOpenAd(
    AdUnitId = openAdId,
    npa = "1", // String | 0 | 1
    responseInfo = false, // boolean

    // Optional
	(info) => { alert(info) }, 
    (error) => { alert(error)}
    );
}`


so what i am missing? can you help?


`

**Comment by emi415064** [comment]
@krestia 

I'm not at home now,
maybe you forgot the square brackets []

version 1.4.2 ()

cordova.plugins.emiAdmobPlugin.loadAppOpenAd(adUnitId = appOpenID, autoShow = false);

version 1.4.4 ([])

cordova.plugins.emiAdmobPlugin.loadAppOpenAd( [adUnitId = appOpenID, autoShow = false ] );

**Comment by krestia** [comment]
@emi415064 
Ok, now it work with weird step,
1. make variable for dynamically change in app runtime : 
`var OPenAdId="";   // i can change the value dynamically in game`
`OPenAdId=<script to call in runtime>;` 
2. make new variable to save value from first variable : 
` var OpenId="";`
`let CallOpen = () => {
    OpenId = OPenAdId }`
3. Get value from the last variable in function to call plugin : 
`CallOpen();  // call to get value from first variable`
`cordova.plugins.emiAdmobPlugin.loadAppOpenAd( [adUnitId = OpenId, autoShow = true ] );`

i don't know why i must use step 2
