### ISSUE TITLE
Event on.get.consent.status not launched / Help needed

### ISSUE THREAD

**Issue by hooliapps** [EMI-INDO/emi-indo-cordova-plugin-admob#22]
Hello

I'm migrating from Cordova (ios) admob plus plugin to this plugin.

I'm trying to use the following code, but i have some problems.
- Event "on.get.consent.status" seems not launched, so i cannot launch "Prepare ads" after consent is given.

* ATT iOS 14 Message is displayed correctly (ok)
* I use Google UMP Form

// 1. Init global settings
cordova.plugins.emiAdmobPlugin.globalSettings(A.admobConfigGlobalSettings);

// 2. Init targeting
cordova.plugins.emiAdmobPlugin.targeting(A.admobConfigTargeting);

// 3 Create Event SDK Init
document.addEventListener('on.sdkInitialization', function() {

	// 3a. I want to ask for iOS14 ATT 
	cordova.plugins.emiAdmobPlugin.requestIDFA(
		function(trackingAuthorizationStatus) {
			console.log('trackingAuthorizationStatus:'+trackingAuthorizationStatus);

			// 3b. I want to ask for Consent form if needed
			cordova.plugins.emiAdmobPlugin.getConsentRequest(
				function(consentStatus) {
					console.log('consentStatus:'+consentStatus);
				},
				function(error) {
					console.log('error:'+error);
				}
			);

		},
		function(error) {
			console.log('error:'+error);
		}
	);

});

// 4. Create Event On TCString expired : Force Consent GDPR
document.addEventListener('on.TCString.expired', function() {
	cordova.plugins.emiAdmobPlugin.consentReset();
});

// 5. When i get consent status --> Prepare Ads
document.addEventListener('on.get.consent.status', function() {
	A.startSdks();
});

// 6. Init Admob plugin
cordova.plugins.emiAdmobPlugin.initialize();

Best regards

**Comment by EMI-INDO** [comment]
@hooliapps 

**I made a little example, like this.**

https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob/blob/main/example/ump_att.html

**Comment by hooliapps** [comment]
Thanks a lot i will try.

**Comment by hooliapps** [comment]
Hello.

I did tests.

At first execution, both forms ATT/CMP are displayed (ok), but on.sdkInitialization event is not launched.
I stop/restart app, then on.sdkInitialization is correctly launched.

Best regards

**Comment by emi415064** [comment]
```
if (status === 0) {


} else if (status === 1) {


} else if (status === 2) {


} else if (status === 3) {


} 

```

https://developers.google.com/admob/android/privacy/api/reference/com/google/android/ump/ConsentInformation.ConsentStatus

**Comment by hooliapps** [comment]
Where can i put this code please ?

I tried to add any code after the initialize part (even with await) then code is launched immediatly when show is displayed, so before user make his choice (click buttons/close forms).

**Comment by EMI-INDO** [comment]
// Here UMP status
                            // Whatever the status is install admob sdk
							
                           if (status === 0) {


} else if (status === 1) {


} else if (status === 2) {


} else if (status === 3) {


} 

https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob/blob/main/example/ump_att.html

**Comment by matrixreal** [comment]
> @hooliapps
> 
> **I made a little example, like this.**
> 
> https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob/blob/main/example/ump_att.html

the link is not working i need that example thanks
got same ios ATT ok but not google ump
every thing is set up on admob also i have added the correct app id

**Comment by EMI-INDO** [comment]
@matrixreal 

It's all here  https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob/blob/main/example/www/js/deviceready.js

All simple examples: https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob/tree/main/example/www/js


```
 // SDK EVENT Initialization
    // Optional
    document.addEventListener('on.sdkInitialization', (data) => {
        // JSON.stringify(data)
        const sdkVersion = data.version;
        // const adAdapter = data.adapters;
        const conStatus = data.consentStatus; // UMP status
        const attStatus = data.attStatus;   // ATT status
        // const gdprApplie = data.gdprApplies;
        // const purposeConsent = data.purposeConsents;
        // const vendorConsents = data.vendorConsents;
        // const conTCString = data.consentTCString;
        // const additionalConsent = data.additionalConsent;
        log.value += ("\n On Sdk Initialization version: " + sdkVersion);
        log.value += ("\n On Consent Status: " + conStatus);
        
        if (isPlatformIOS){
            
            log.value += ("\n On Authorization Status: " + attStatus);
        }


    });

```
