### ISSUE TITLE
Load fail event is not triggered

### ISSUE THREAD

**Issue by merbin2012** [EMI-INDO/emi-indo-cordova-plugin-admob#30]
I have seen this issue before, but I am not concerned about it due to some other testing on this plugin.

Ad load error, return the following errors

`cordova.fireDocumentEvent('on.appOpenAd.failed.loaded, {"responseInfo":"{\n  \"Response ID\": \"null\",\n  \"Mediation Adapter Class Name\": \"\",\n  \"Adapter Responses\": [],\n  \"Response Extras\": {}\n}","code":3,"message":"Ad unit doesn't match format. <https:\/\/support.google.com\/admob\/answer\/9905175#4>","domain":"com.google.android.gms.ads","cause":"null"}');`

Escape character issue, you can just copy the above code and paste it to the VSC in .js file.

The same thing I was seen for interstitial ads too, I think the same issue is existing in banner and other ads too.

![error screenshot](https://github.com/user-attachments/assets/be219f3d-4ccc-49fb-b381-2c5e5296e716)
![error screenshot 2](https://github.com/user-attachments/assets/f206cef2-1c1a-46c6-b493-95feda04b748)

`"javascript:cordova.fireDocumentEvent('on.interstitial.failed.load', ${errorData});"`
`"javascript:cordova.fireDocumentEvent('on.interstitialAd.responseInfo', ${result});"`
`"javascript:cordova.fireDocumentEvent('on.appOpenAd.failed.loaded, ${errorData}');"`
`"javascript:cordova.fireDocumentEvent('on.interstitial.revenue', ${result});"`
....
....
....
and etc.. places. Please fix this

I just get this from chatGPT, please check and update it
```
val escapedErrorData = errorData.replace("\"", "\\\"").replace("\n", "\\n")
cWebView!!.loadUrl(
    "javascript:cordova.fireDocumentEvent('on.appOpenAd.failed.loaded', \"$escapedErrorData\");"
)
```

**Comment by EMI-INDO** [comment]
`emi-indo-cordova-plugin-admob@1.6.4`

- Note release https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob/releases

### Users should use their own methods

- maybe this helps a little
```
<script src=“https://cdn.jsdelivr.net/npm/json5@2.2.1/dist/index.min.js”></script>
```
document.addEventListener('on.interstitialAd.responseInfo', (data) => {

- Cleansing data from unnecessary or invalid characters
- Solve the escape character problem

});

**Comment by merbin2012** [comment]
This is not a javascript side problem, while we calling the javascript method from java code, so we have to handle it from java code. The above mentioned code is kotlin

**Comment by EMI-INDO** [comment]
sorry I only fixed Load fail event is not triggered

I tested the method you suggested doesn't work on a real device.
```
val escapedErrorData = errorData.replace("\"", "\\\"").replace("\n", "\\n")
cWebView!!.loadUrl(
    "javascript:cordova.fireDocumentEvent('on.appOpenAd.failed.loaded', \"$escapedErrorData\");"
)
```

**Comment by merbin2012** [comment]
No, I'm not tested . Did you understand the error?
If not just copy and paste this code in visual studio code, you can exactly identify the issue.

`cordova.fireDocumentEvent('on.appOpenAd.failed.loaded, {"responseInfo":"{\n  \"Response ID\": \"null\",\n  \"Mediation Adapter Class Name\": \"\",\n  \"Adapter Responses\": [],\n  \"Response Extras\": {}\n}","code":3,"message":"Ad unit doesn't match format. <https:\/\/support.google.com\/admob\/answer\/9905175#4>","domain":"com.google.android.gms.ads","cause":"null"}');
`
This is the code created in kotlin. Here it is 4AM, I'm in mobile, I will also try to fix it while I'm in the system.

**Comment by EMI-INDO** [comment]
I tested several times with the original adUnitId, everything was fine.

I don't get any error

- try checking again whether adUnitId is really adUnitId AppOpenAd.

- or try creating a new adUnitId.

https://groups.google.com/g/google-admob-ads-sdk/c/T7uNaa7AoFo


https://github.com/googleads/googleads-mobile-android-examples/issues/626

**Comment by merbin2012** [comment]
This issue is not related to that. Whenever call the javascript methode from kotlin with the error details as a parameter this issue is occurring. I think it is easy to solve, I will check and let you know the status.

**Comment by merbin2012** [comment]
@EMI-INDO Great, this issue has been resolved.
Thank you
