### ISSUE TITLE
unable to build admobplus with firebasex

### ISSUE THREAD

**Issue by brunoalex** [EMI-INDO/emi-indo-cordova-plugin-admob#36]
cant build with firebasex ... 

admob-plus-cordova 2.0.0-alpha.19 "admob-plus-cordova"
 
always get this error ... 
* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : Attribute property#android.adservices.AD_SERVICES_CONFIG@resource value=(@xml/gma_ad_services_config) from [com.google.android.gms:play-services-ads-lite:23.2.0] AndroidManifest.xml:92:13-59
        is also present at [com.google.android.gms:play-services-measurement-api:21.5.0] AndroidManifest.xml:32:13-58 value=(@xml/ga_ad_services_config).
        Suggestion: add 'tools:replace="android:resource"' to <property> element at AndroidManifest.xml to override.

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
Could be related to the first two issues discussed here;

https://github.com/admob-plus/admob-plus/issues?q=is%3Aopen+firebasex

* https://github.com/admob-plus/admob-plus/issues/672
* https://github.com/admob-plus/admob-plus/issues/646

**Comment by EMI-INDO** [comment]
### remove

`cordova plugin rm emi-indo-cordova-plugin-admob`

### Installation

`cordova plugin add https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob`

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
> `remove platform`
> 
> ### remove plugin
> `cordova plugin rm emi-indo-cordova-plugin-admob`
> 
> ### Installation
> `cordova plugin add https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob`

Thx for fixing, it seems related to "the other" plug-in (basically, the core is the same of course).

**Comment by brunoalex** [comment]
<plugin name="cordova-plugin-firebasex" spec="latest">
        <variable name="FIREBASE_VERSION" value="12.0.0" />
    </plugin> 

 <config-file parent="./application" target="AndroidManifest.xml">
            <property android:name="android.adservices.AD_SERVICES_CONFIG" android:resource="@xml/gma_ad_services_config" tools:replace="android:resource" />
        </config-file>

and  xmlns:tools="http://schemas.android.com/tools" fixed the issue tks u both

**Comment by EMI-INDO** [comment]
NPM Already released `emi-indo-cordova-plugin-admob@1.6.7`

Now everything is automatic, no manual confirmation is required.

**Comment by EMI-INDO** [comment]
@1n3JgKl9pQ6cUMrW @brunoalex 

I didn't want this plugin to become dependent on other plugins to solve the problem, so to solve this problem I created a new plugin.

### This will solve the problem in 
- admob-plus-cordova
- community-admob-plus
- emi-indo-cordova-plugin-admob

### Install
```
cordova-admob-firebase-fix
```

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
> @1n3JgKl9pQ6cUMrW @brunoalex
> 
> I didn't want this plugin to become dependent on other plugins to solve the problem, so to solve this problem I created a new plugin.
>  (...)
> ### Install
> ```
> cordova plugin add cordova-admob-firebase-fix
> ```

I downloaded and installed the plug-in. It seems to hook the install-proces, to automatically inject some codes in the .xml file?

I used to do this by hand, but only for the (other) plug-in;

https://github.com/admob-plus/admob-plus

From what I understand, your fix supports that plug-in. But is it (also) needed for your own Admob plug-in?

Or has it that "plug-in fix" build inside?

Is there a public repro where we can find the new plug-in (the Firebase fix, I mean). Now it's only accessible from the command line, but not on Git(hub).

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
> ### You can test it like this
> ```
> cordova plugin add cordova-plugin-firebasex
> cordova plugin add admob-plus-cordova
> ```
> 
> ### build error
> ```
> Execution failed for task ':app:processDebugMainManifest'.
> > Manifest merger failed : Attribute property#android.adservices.AD_SERVICES_CONFIG@resource value=(@xml/gma_ad_services_config) from [com.google.android.gms:play-services-ads-lite:23.2.0] AndroidManifest.xml:92:13-59
>         is also present at [com.google.android.gms:play-services-measurement-api:22.0.2] AndroidManifest.xml:32:13-58 value=(@xml/ga_ad_services_config).
>         Suggestion: add 'tools:replace="android:resource"' to <property> element at AndroidManifest.xml to override.
> ```
> 
> ### Install
> ```
> cordova plugin add cordova-admob-firebase-fix
> ```
> 
> * successful build

Yeah, I tested it 💯 

But this is not for your own plug-in, since it has this hook build inside?

**Comment by EMI-INDO** [comment]
I made it for any cordova admob plugin that gets an error like the above

I tried adding it directly into the `plugin.xml`  xmlns:tools="http://schemas.android.com/tools 

after that` cordova plugin add cordova-plugin-firebasex` it will generate a duplicate xmlns:tools="http://schemas.android.com/tools 

if with hooks it's easier because if xmlns:tools="http://schemas.android.com/tools already exists hooks will skip it.

**Comment by EMI-INDO** [comment]
duplicate xmlns:tools="http://schemas.android.com/tools in android studio may not be a problem, but it will not be solved by cloud builds, such as https://volt.build/

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
Thanks for doing this work.

Sometimes, I can be quit a mess with all those plug-ins, repo's and hooks :-)

**Comment by EMI-INDO** [comment]
I made new hooks,
in some cases this may also be necessary

https://www.npmjs.com/package/cordova-remove-aaid-permission
