### ISSUE TITLE
Error on1.6.8 & 1.6.7 version

### ISSUE THREAD

**Issue by merbin2012** [EMI-INDO/emi-indo-cordova-plugin-admob#38]
Error on the following line
`<property android:name="android.adservices.AD_SERVICES_CONFIG" android:resource="@xml/gma_ad_services_config" tools:replace="android:resource"/>`

We do not create the `@xml/gma_ad_services_config` in default. So what should I do?

![Error](https://github.com/user-attachments/assets/8a0201c0-50de-40e0-b481-73554fc4c261)

**Comment by merbin2012** [comment]
> I'm preparing a new release in the next few hours. [e0931ca](https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob/commit/e0931cac06aeff85a078d585a7563a3cc4f4aa12)
> 
> for now `cordova plugin add https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob`

Okay Thank you

**Comment by EMI-INDO** [comment]
Already released `emi-indo-cordova-plugin-admob@1.6.9`

**Comment by merbin2012** [comment]
Now it is working with this 1.6.9 version
