### ISSUE TITLE
Content overlapping issue

### ISSUE THREAD

**Issue by merbin2012** [EMI-INDO/emi-indo-cordova-plugin-admob#45]
The content overlapping issue is still present on many devices. I have tried various solutions, but none have worked. This could lead to receiving an AdMob violation notification from Google.

`cordova.plugins.emiAdmobPlugin.styleBannerAd({isOverlapping: _isOverlappingEnable, overlappingHeight: _overlappingHeight, padding:65, margins: 65 }); `

The value "65" is hardcoded, but it should not be, as it needs to vary depending on the device. Please try to find a solution for this.

**Comment by merbin2012** [comment]
I think I have fixed this issue. The reason is we need to find the navigational bar height from native code and set it to margin or both (divide the navigation bar height and set it to both the same value)


In my **oppo** device with the below option
`cordova.plugins.emiAdmobPlugin.styleBannerAd({isOverlapping: _isOverlappingEnable, overlappingHeight: _overlappingHeight, padding: 0, margins: 65 }); `

![Oppo](https://github.com/user-attachments/assets/3030671a-0f15-4304-b1e8-135a7b8f90ff)

With the following option
`cordova.plugins.emiAdmobPlugin.styleBannerAd({isOverlapping: _isOverlappingEnable, overlappingHeight: _overlappingHeight, padding: 0, margins: 88 }); `

![Oppo_correct value](https://github.com/user-attachments/assets/c906115a-b835-42ff-8e4b-51b46f458e7b)

Here 88 is the correct value, the value is can get it from modified code (No need to set it from `.styleBannerAd` method)

![Oppo_Android_studio](https://github.com/user-attachments/assets/2688011c-5080-4a7e-be7c-d4ceaa17d404)


In my **Redmi Note 5 Pro** device
With the following option
`cordova.plugins.emiAdmobPlugin.styleBannerAd({isOverlapping: _isOverlappingEnable, overlappingHeight: _overlappingHeight, padding: 0, margins: 88 }); `
![Redmi note 5 pro_85 png](https://github.com/user-attachments/assets/69cfb7a0-c270-4c9c-8ebb-5bb6fc89640e)

With the following option
`cordova.plugins.emiAdmobPlugin.styleBannerAd({isOverlapping: _isOverlappingEnable, overlappingHeight: _overlappingHeight, padding: 0, margins: 130 }); `

![Redmi note 5 pro_correctAd](https://github.com/user-attachments/assets/6e81b571-6f4b-47b8-8eaa-53dd89e8cdcb)


In android studio
![Redmi note 5 pro_Android Studio](https://github.com/user-attachments/assets/ae33eb4b-e181-4b1a-928e-ed75e88caba2)


In the sameway I have tested in Redmi 11 T Pro, that is also working fine. Tomorrow I can test with two more Samsung devices and one more huawei tab.


The code is 
```
                    val metrics = cordova.activity.resources.displayMetrics
                    val screenHeight: Int
                    val usableHeight: Int

                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
                        val windowMetrics = cordova.activity.windowManager.currentWindowMetrics
                        val insets = windowMetrics.windowInsets.getInsetsIgnoringVisibility(WindowInsets.Type.navigationBars())
                        screenHeight = windowMetrics.bounds.height()
                        usableHeight = screenHeight - insets.bottom


                    } else {
                        val display = cordova.activity.windowManager.defaultDisplay
                        val size = Point()
                        val realSize = Point()
                        display.getSize(size)
                        display.getRealSize(realSize)

                        usableHeight = size.y
                        screenHeight = realSize.y
                    }

                    val navBarHeight=screenHeight - usableHeight




                    val paddingPx = options.optInt("padding")
                    val marginsPx = options.optInt("margins")
                    try {
                        this.isOverlapping = isOverlapping
                        this.overlappingHeight = overlappingHeight
                        this.paddingInPx = paddingPx
                        this.marginsInPx = navBarHeight//marginsPx
                    } catch (e: Exception) {
                        callbackContext.error(e.toString())
                    }
```

**Comment by EMI-INDO** [comment]
I will immediately send the new release to production v1.8.9

Allows plugin users to have full control before loading or displaying banner ads.

**Comment by merbin2012** [comment]
@EMI-INDO Did you check it in your device? Is it worked?

**Comment by EMI-INDO** [comment]
Release: https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob/releases/tag/v.1.8.9

Yes I tested it on a working emulator and made slight adjustments to your code, is that correct, if wrong get back to me.

- This change affects

```
cordova.plugins.emiAdmobPlugin.styleBannerAd({
            isOverlapping: true, 
            overlappingHeight: 0, // default 0 (Automatic)
            padding: 0, // default 0
            margins: 0 // default 0 (Automatic)
        });
```

**Comment by merbin2012** [comment]
Okay. Tomorrow I'll test and let you know.

**Comment by merbin2012** [comment]
**Redmi Note 5 Pro (Android 9)**  
<img src="https://github.com/user-attachments/assets/de9f9fdd-c024-4898-a9b0-3c68e33510db" alt="Redmi Note 5 Pro" width="200">

**Samsung A15 (Android 14)**  
<img src="https://github.com/user-attachments/assets/965fec0c-2f57-442c-ad72-9b6d6d137310" alt="Samsung A15" width="200">

**Samsung M34 (Android 14)**  
<img src="https://github.com/user-attachments/assets/f6698fc3-dff8-4a1e-978d-c04133d70d59" alt="Samsung M34" width="200">

**Vivo Y21 (Android 11)**  
<img src="https://github.com/user-attachments/assets/759fb614-3e08-4375-a8f7-6cd5fec97e02" alt="Vivo Y21" width="200">

**Huawei Tab (Android 7)**  
<img src="https://github.com/user-attachments/assets/36a964a9-2b53-4fc0-9e38-399371d0981d" alt="Huawei Tab" width="200">

**Redmi 6A (Android 10)**  
<img src="https://github.com/user-attachments/assets/54d2566f-1584-4196-bfcd-fdfef14b9729" alt="Redmi 6A" width="200">

**Redmi 11T Pro (Android 14)**  
<img src="https://github.com/user-attachments/assets/b88fb1e5-8784-455d-ac66-3700adbc6b55" alt="Redmi 11T Pro" width="200">

**Amazon 11 Inch Tab**  
<img src="https://github.com/user-attachments/assets/0bdd82f7-10d2-4043-8ba2-d3d8680ddd0f" alt="Amazon Fire OS" width="200">

**Oppo (Android 14)**  

All are working perfectly.
