### ISSUE TITLE
Commits

### ISSUE THREAD

**Issue by fredriksthlm** [EMI-INDO/emi-indo-cordova-plugin-admob#5]
Hi @EMI-INDO , seems your plugin is progressing fine. Nice to see.

One thing, your commits to the javafile is not working orrectly. Seems like you copy paste the entire file every time, so it is not possible to follow the updates in the commits your are doing, since the entire file is marked as 'changed' every time, since your file is pasted without any line breaks (so the whole file is just one line). The js files and html are correct. See this example: https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob/commit/97bf8ccaf1ffefc23a3f1757a999148065a4db09

One other function your should add is the "mute"-function:
MobileAds.setAppMuted(true);
You can check how Ratson implemented it back in time in his plugin.

Looks promising, thank you!

**Comment by EMI-INDO** [comment]
@fredriksthlm 

everything is correct.

 I intentionally Minify Java files,
And make it 1 line.
https://www.aspect-ratios.com/minify-java/

What changes I made are written in each release.
https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob/releases

No need to check java file commit.

MobileAds. setAppMuted(true); already available,
.everything is already in the Java file,
It's not time for new features to be released,

 all I have to do is make a new line in www/js.file, the new features in the Java file will runrun.

**Comment by EMI-INDO** [comment]
@fredriksthlm 

Your request  MobileAds.setAppMuted(true);

https://github.com/EMI-INDO/emi-indo-cordova-plugin-admob/releases/tag/v.1.0.9
